//title,maxlength,regex
export const record_titles_fields = [
  ["treasurySymbol", 15, true],
  ["groupOfAllocations", 3, true],
  ["appropriationCode", 3, true],
  ["fiscalYear", 10, true],
  ["allotteeCode", 1, true],
  ["majorClassCode", 2, true],
  ["objectClassCode", 2, true],
  ["programPlanningBudgetingCode", 3, true],
  ["obligationExpendituresCode", 3, true],
  ["loans", 0, false],
  ["curVchrAmount", 0, false],
  ["curOblAmount", 0, false],
  ["curAlotAmount", 0, false],
  ["prVchrAmount", 0, false],
  ["prOblAmount", 0, false],
];
export const record_titles = [
  "*TS",
  "GOA",
  "*AC",
  "*FY",
  "*A",
  "*MC",
  "*OC",
  "*PPB",
  "*O&E",
  "Loans",
  "Vouchers",
  "Obligations",
  "Allotments",
  "Vouchers",
  "Obligations",
];
